[package]
name = "bandersnatch-ring-vrf"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-vrf = { git = "https://github.com/davxy/ark-vrf", tag = "v0.1.0", features = ["bandersnatch", "ring", "parallel"] }

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.28"
